# Set the base image to Ubuntu
FROM ubuntu:trusty

MAINTAINER Rafael dos Passos Fortes <rafael.pfortes@gmail.com>

# Install Node.js and other dependencies
RUN apt-get update && \
    apt-get -y install curl && \
    curl -sL https://deb.nodesource.com/setup | sudo bash - && \
    apt-get -y install python build-essential nodejs

# Install nodemon
RUN npm install -g nodemon

# Define working directory
ADD src/ /src
WORKDIR /src

# Provides cached layer for node_modules
ADD package.json /tmp/package.json
RUN cd /tmp && npm install express --save && npm install redis --save && npm install -g grunt-cli && npm install -g bower
RUN mkdir -p /src && cp -a /tmp/node_modules /src/

# Expose port
EXPOSE  8080

# Run app using nodemon
CMD ["nodemon", "index.js"]